services:
  - type: web
    name: tryak-gateway
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        value: ""
      - key: BOT_TOKEN
        value: ""
      - key: BOT_PASSWORD
        value: ""
      - key: ADMIN_CHAT_IDS
        value: ""
      - key: PUBLIC_DOMAIN
        value: ""
